/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBreadthRouteImport } from './routes/api/breadth'
import { Route as ApiCoilRouteImport } from './routes/api/coil'
import { Route as ApiDeskRouteImport } from './routes/api/desk'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiVenuesRouteImport } from './routes/api/venues'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBreadthRoute = ApiBreadthRouteImport.update({
  id: '/api/breadth',
  path: '/api/breadth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoilRoute = ApiCoilRouteImport.update({
  id: '/api/coil',
  path: '/api/coil',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeskRoute = ApiDeskRouteImport.update({
  id: '/api/desk',
  path: '/api/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVenuesRoute = ApiVenuesRouteImport.update({
  id: '/api/venues',
  path: '/api/venues',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/breadth': typeof ApiBreadthRoute
  '/api/coil': typeof ApiCoilRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/export': typeof ApiExportRoute
  '/api/venues': typeof ApiVenuesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/breadth': typeof ApiBreadthRoute
  '/api/coil': typeof ApiCoilRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/export': typeof ApiExportRoute
  '/api/venues': typeof ApiVenuesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/breadth': typeof ApiBreadthRoute
  '/api/coil': typeof ApiCoilRoute
  '/api/desk': typeof ApiDeskRoute
  '/api/export': typeof ApiExportRoute
  '/api/venues': typeof ApiVenuesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/breadth'
    | '/api/coil'
    | '/api/desk'
    | '/api/export'
    | '/api/venues'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/breadth'
    | '/api/coil'
    | '/api/desk'
    | '/api/export'
    | '/api/venues'
  id:
    | '__root__'
    | '/'
    | '/api/breadth'
    | '/api/coil'
    | '/api/desk'
    | '/api/export'
    | '/api/venues'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBreadthRoute: typeof ApiBreadthRoute
  ApiCoilRoute: typeof ApiCoilRoute
  ApiDeskRoute: typeof ApiDeskRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiVenuesRoute: typeof ApiVenuesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/breadth': {
      id: '/api/breadth'
      path: '/api/breadth'
      fullPath: '/api/breadth'
      preLoaderRoute: typeof ApiBreadthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coil': {
      id: '/api/coil'
      path: '/api/coil'
      fullPath: '/api/coil'
      preLoaderRoute: typeof ApiCoilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/desk': {
      id: '/api/desk'
      path: '/api/desk'
      fullPath: '/api/desk'
      preLoaderRoute: typeof ApiDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/venues': {
      id: '/api/venues'
      path: '/api/venues'
      fullPath: '/api/venues'
      preLoaderRoute: typeof ApiVenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBreadthRoute: ApiBreadthRoute,
  ApiCoilRoute: ApiCoilRoute,
  ApiDeskRoute: ApiDeskRoute,
  ApiExportRoute: ApiExportRoute,
  ApiVenuesRoute: ApiVenuesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
